Improve error message display by leveraging Spring Boot JSON errors
Spring Boot provides JSON error messages by default, that are easier to
parse on the PXF C-client. We add support for Spring Boot error
messages, and enhance error messages with error HINTs provided to the
end user. This also gave us the opportunity to improve some of the error
messages and enhance them with useful hints.

This commit also fixes automation tests that have been neglected for a
while, but now there's only 1 test that is failing 50% of the time
(which we will address later). The failing test is
`HdfsReadableTextTest.limit` which seems to be related to the fact that
we are doing limit.

This commit also makes sure that the TaskExecutorPool is correctly
configured and is properly hooked to the ShutdownHook. Before this fix,
the application would take a long time to shutdown because of running
threads.

Also, we improve the doAs call. It turns out that for the Bridge
creation we also need to perform a doAs, this is specially critical in
a keberized environment.

As part of fixing the automation tests, we have started adding
transitive dependencies that were neglected for a while. We also make
sure that they do not bring transitives themselves by marking them with
`{ transitive = false }`.

Co-authored-by: Francisco Guerrero <aguerrero@pivotal.io>
Co-authored-by: Alexander Denissov <adenissov@pivotal.io>
Co-authored-by: Lisa Owen <lowen@pivotal.io>

diff --git a/server/Makefile b/server/Makefile
--- a/server/Makefile
+++ b/server/Makefile
@@ -84,6 +84,14 @@ install: stage
 	mkdir -p "$(PXF_HOME)"
 	cp -R build/stage/pxf/* "$(PXF_HOME)"
 
+.PHONY: install-dev
+install-dev: stage-notest
+	@if [ -z "$(PXF_HOME)" ]; then \
+		echo "ERROR: PXF_HOME is not set"; exit 2; \
+	fi
+	mkdir -p "$(PXF_HOME)"
+	cp -R build/stage/pxf/* "$(PXF_HOME)"
+
 .PHONY: version
 version:
 	@./gradlew -q version
